spring:
    application:
        name: dulian
    profiles:
        active: ${profile}
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
jwt:
    secret: ENC(QEWIuRZd31xzDx1LjKLpyzKe12HqG2fXaawlV2gLULz1Pfx+q0uVyqgfUymLtKedgF2MsqYaraz9wWyLOkHDGIZaQL9jTTV/37IkSBpG+Hc=)
springdoc:
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
    swagger-ui:
        url: /docs/openapi3.yaml
        path: /docs/swagger
file:
    image-extensions: jpg,jpeg,png,heic
