spring:
    config:
        activate:
            on-profile: dev
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC(isVMqUQsnSOwUQsIeu0oSSxa1OtErRz175lUmCR2PVzUZ0i3NCLmk7xLjb0JglPRtqJOTWu4aJjhm2rjmunawFz2zqHZVR/JGN3YkQu7Mmmv/SXeFPHc5V+r+mpcKrog)
        username: ENC(Bhp3BJciwTKF6xvvwTp9Pw==)
        password: ENC(QXcsWGbSzkLYbV7+vnTnL1zwMsQh4/Gs)
    jpa:
        hibernate:
            ddl-auto: validate
    mail:
        username: noreply@dulian.kr
        mailjet:
            api-key: ENC(fkEgtAuS1J+DsnGdcUrJhS8rqHk1TsAe5cFuzHIwxya+2Smt6DI4FFztq2itbqnA)
            secret-key: ENC(y5YUIwN26uLcv10HSn96jHszgUiQebXadQow1wKJc8vouo3g6asWZlLFJTSwZX5h)
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ENC(eFR93rrQ1WlXAWNWPxbKv1jH0XMI18N5BRDB3dq3ty+r8185TfX1V/cPenwlfe2r)
                        client-secret: ENC(wiPrapXSTgLMD4+OyZMMp3LTHporVPLP+YqEUmr7FhdvcpA3RW84BVTnl+vI1BRU)
                        redirect-uri: ENC(toPbZFkzxhYD6MO6EHSPCtHyPnff4Lg3xJKoQ+PPnAMVgzvlruFy5XY09vc3+fMQHOolEC1PxsY=)
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        client-name: Kakao
                    naver:
                        client-id: ENC(DOq8CnysGGhcUKyy0K+N4AWKxJF+q9teKgMOMTYRRuE=)
                        client-secret: ENC(H9spIRI51P10qm+b6pBWMaYNWrdf+JHv)
                        redirect-uri: ENC(zqw7UWWieBu90QIjQQhyc4S2QDD6l7BPB2vy3ujJoNr2Q6maXt5qEHfbjzhKaLFscXr7v4Tm17U=)
                        authorization-grant-type: authorization_code
                        client-name: Naver
                    google:
                        client-id: ENC(hLP34gG0ISq+rq44tjo+ZbbKpAlLxz5lH2C0ZGDqqzHAiH9wgwq7piza4VBFy865AGEPpCN3aTEqwjqLg4ErIA3cZcabZCt4buul+tDarGUAaG9uc6RTCw==)
                        client-secret: ENC(iS4PDWZDoI6bAH9vdiEagkPH/At682TJn79mkL208f3snU0vNLG+ne0INJa83J82)
                        redirect-uri: ENC(N4LFx8LIRiqRUzdaVTe0OMqxMb3JB06WfacmOvw9OvTptIZYxzaHOHsX9k53TGhTGz2wwoEtbL8=)
                        scope:
                            - email
                            - profile
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response

jwt:
    access-token-expiration: 1800 # 30분
    refresh-token-expiration: 604800 # 7일
oauth2:
    redirect-url: ENC(YdFoDd+MI8RpMvk8lafkycDd1XD17thhXU1ZEZQWkxOphCs105IuMpYeBY7a6Zlh)
