spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC(h7PAHpEJNhEM/SrG/UW9pSBHQmQlevdHleG1/5sx7jNViNf8gDLe38oewiGDVu0c47A5sDh/tUQ=)
        username: ENC(Bhp3BJciwTKF6xvvwTp9Pw==)
        password: ENC(QXcsWGbSzkLYbV7+vnTnL1zwMsQh4/Gs)
