spring:
    config:
        activate:
            on-profile: local
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ENC(m67CqpzFei+YdJ2EIi+Vwm4hzePF6r1T3SJ3OiGGWseDMPNmt/1xRu9wj7ega3WNFk+dW3xbDuc=)
        username: ENC(Bhp3BJciwTKF6xvvwTp9Pw==)
        password: ENC(QXcsWGbSzkLYbV7+vnTnL1zwMsQh4/Gs)
    jpa:
        hibernate:
            ddl-auto: update
    mail:
        username: noreply@dulian.kr
        mailjet:
            api-key: ENC(fkEgtAuS1J+DsnGdcUrJhS8rqHk1TsAe5cFuzHIwxya+2Smt6DI4FFztq2itbqnA)
            secret-key: ENC(y5YUIwN26uLcv10HSn96jHszgUiQebXadQow1wKJc8vouo3g6asWZlLFJTSwZX5h)
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ENC(6dPIVos3Gj1JSCHwko7+94vLV4BGs5DmYpTA0GfcMljLOQ8YHbjwjPZLPKqRxDhg)
                        client-secret: ENC(iH1SMza6lYp/01K8cDdfS1zSoFPP1FEkU1VHE0IiyGtxZzkOw8+8TZz1CJ9ukQIv)
                        redirect-uri: ENC(+5p7LXWMZx1S7l0cUYjMkRLdksE3lsF7bVcQgVNSpz00Z0mjr3KXgfPj8o8zeIciQCZ6v4eVpEw=)
                        client-authentication-method: client_secret_post
                        authorization-grant-type: authorization_code
                        client-name: Kakao
                    naver:
                        client-id: ENC(hpzJMvInEqFHNMi4gNqlF9h6IzTNiXdkjXg0K35mvlk=)
                        client-secret: ENC(fsTfLlQ2CdjVKmPjzrROAV2Wt+LSdpH2)
                        redirect-uri: ENC(kZsa++Gdd8h6WsWQEXbL5yO8iUeF15AaAdalAtSnGc8WcNSVZxx2LldHrY6MeMtxZiXFur6cj9Y=)
                        authorization-grant-type: authorization_code
                        client-name: Naver
                    google:
                        client-id: ENC(+mEetIazyZvG8BCcMuDjzr0zdBjJJKvrGMeh1W9uy7IITaFBP+7JgSBMeK7fzuTLwSFlgLD7yhmagofN17RrLjxMCcN85qg0f45ILf2bjrPipDNTDf+pXQ==)
                        client-secret: ENC(/sH+qjlDomzhxQ3OfH1+Rd89VRSXuRYCL/DwyokocoPXj0Uqzq3sD/se+Dvu1Tm1)
                        redirect-uri: ENC(SBzMOrirqZSzd78XZKNFozdJU1uYkpMGWZIfLp/IPkoMjbKcvPVbfK0Sf2dmvcp4H4RKalc+xug=)
                        scope:
                            - email
                            - profile
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
jwt:
    access-token-expiration: 1800 # 30분
    refresh-token-expiration: 604800 # 7일
oauth2:
    redirect-url: ENC(S7eKe1zzMNS6NBvM/JsrZg02CC3tQAHb1B4zxfbgo0sjNHiTHVtyOQSv/KPe6JqQ)
cloud:
    aws:
        s3:
            bucket: ENC(8TtH6zxSx7qz6f3FEWfk8XCRKn0QO7dl)
            region.static: ENC(z+3/W5lP5K6RPxqWN8HX1ZswBJQPn+JC)
            stack.auto: false
            credentials:
                access-key: ENC(GPIDwoFZ0HHtcdDnY7pF+fwH/i4ZGOMfUioBR7jMVRo=)
                secret-key: ENC(cXirqUbAcuFILdIapW5HNX4UKHkDpeRx8QJHCXjtwS9piw5tmZmf+3FH32PXXT8JLwNTvBo7GuI=)
            url: ENC(H1gQp8GG9Cu+vciZbqtpOvyZ1nbf99LXVfK6ios6PRlbNp3LWtr6ZdJCT2U29RKG+vJjNKETLFWD4i3PHhiiSA==)
